#!/bin/sh
# The deployment section should be excluded until
# it is explicitly included in module 5
version: 2.0
jobs:
 build:
   docker:
     - image: node:8.12
   steps:
     # checkout branch
     - checkout
     - run:
         name: The Second Step
         command: |
           echo 'Hello World!'
           echo 'This is the delivery pipeline'
     - setup_remote_docker
     - run:
         name: Install Docker client
         command: |
           set -x
           VER="17.03.0-ce"
           curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
           tar -xz -C /tmp -f /tmp/docker-$VER.tgz
           mv /tmp/docker/* /usr/bin
     - run:
         name: Build Docker image
         command: docker build -t plasmawolf/pluralsight-docker-ci:$CIRCLE_SHA1 .
     - run:
         name: Push to DockerHub
         command: |
            docker login -u$DOCKERHUB_LOGIN -p$DOCKERHUB_PASSWORD
            docker push plasmawolf/pluralsight-docker-ci:$CIRCLE_SHA1
     #just an additional change to test pushing to DockerHub
     # - run:
     #   name: The Zeroeth step
     #   command: |
     #      apk update && apk add curl curl-dev bash
     #      echo "Install curl and update system"
     #
     # - run:
     #   name: The First step BUILD
     #   command: |
     #    $ docker build Dockerfile

     # - run:
     #     name: The Second Step
     #     command: |
     #       echo 'Hello World!'
     #       echo 'This is the delivery pipeline'
     #       sh -c "$DOCKER_HUB_TRIGGER"
     #       echo 'DOCKER image sent to DOCKERHUB'



#          bash -c "$DOCKER_HUB_TRIGGER"
# source $DOCKER_HUB_TRIGGER

# deployment:
#   dockerhub:
#     branch: master
#     commands:
#      - $DOCKER_HUB_TRIGGER
#
# test:
#   override:
#     - mocha
