# The deployment section should be excluded until
# it is explicitly included in module 5
version: 2.0
jobs:
 build:
   docker:
     - image: alpine:3.7
   steps:
     - run:
         name: The First Step
         command: |
           echo 'Hello World!'
           echo 'This is the delivery pipeline'
           bash -c "$DOCKER_HUB_TRIGGER"
# source $DOCKER_HUB_TRIGGER

# deployment:
#   dockerhub:
#     branch: master
#     commands:
#      - $DOCKER_HUB_TRIGGER
#
# test:
#   override:
#     - mocha
