#!/bin/sh
# The deployment section should be excluded until
# it is explicitly included in module 5
version: 2.0
jobs:
 build:
   docker:
     - image: alpine:3.7
   steps:
     # checkout branch
     - checkout
     - run:
       name: The Zeroeth step
       command: |
          apk update && apk add curl curl-dev bash
          echo "Install curl and update system"

     - run:
       name: The First step BUILD
       command: |
        $ docker build Dockerfile

     - run:
         name: The Second Step
         command: |
           echo 'Hello World!'
           echo 'This is the delivery pipeline'
           sh -c "$DOCKER_HUB_TRIGGER"
           echo 'DOCKER image sent to DOCKERHUB'



#          bash -c "$DOCKER_HUB_TRIGGER"
# source $DOCKER_HUB_TRIGGER

# deployment:
#   dockerhub:
#     branch: master
#     commands:
#      - $DOCKER_HUB_TRIGGER
#
# test:
#   override:
#     - mocha
